### ISSUE TITLE
will there be a version of the program for the main 1.7.10

### ISSUE THREAD

**Issue by imofey** [WearBlackAllDay/SeedCandy#10]
.

**Comment by WearBlackAllDay** [comment]
1.12 and below require 2 dungeons for meaningful reversal, its not impossible to add i plainly havent done it, will maybe do that at some point if people find that useful

**Comment by Shar1ck** [comment]
> 

Hello! bro you have a very cool and useful program but it is very lacking for 1.7.10...
a google search shows that many people are looking for version 1.7.10...
And a lot of people are looking for a way to find out the seed for him.
Honestly I would like to see the version on 1.7.10 =)
I even had to register to write something :))
