### ISSUE TITLE
Wish I knew how to use it

### ISSUE THREAD

**Issue by chadandersen1** [WearBlackAllDay/SeedCandy#5]
Literally what the tittle says, there is no documentation on actually running the program and I know very little about coding so I have no idea what to do other than try to open the jar file. I would like to use some of the features, someone please explain how to open the program

**Comment by chadandersen1** [comment]
fix is to install java 16. Not everyone has it, would be nice if the readme said it was required.

**Comment by kekkill** [comment]
я установил джаву 16 но что дальше? я попробовал нажать на файл но ничего не произошло
