### ISSUE TITLE
when update to 1.18

### ISSUE THREAD

**Issue by BlackSilec** [WearBlackAllDay/SeedCandy#8]
Will there be an update to version 1.18?

**Comment by WearBlackAllDay** [comment]
1.18 sadly made it impossible (very hard) to reverse decorator (dungeon) information.

**Comment by t4ebrian** [comment]
Any progress?

**Comment by WearBlackAllDay** [comment]
i will add it if i get the time to do it and it turns out to be in a reasonable time
either way 1.18 is a completely special case from all previous versions

**Comment by binni0r** [comment]
i mean, i can wait, it's not a problem in this case. but how much will it take you to release your genius program on 1.18.x?

**Comment by t4ebrian** [comment]
is it possible to calculate the world's seed with double generation?

**Comment by binni0r** [comment]
when is 1.18.1 gonna release?

**Comment by binni0r** [comment]
i need to ruin a p2w server.
